"""add pipeline_runs and pulsar_snapshots

Revision ID: 1967312839a2
Revises: bdf902864461
Create Date: 2026-09-19 21:34:27.757149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1967312839a2'
down_revision: Union[str, Sequence[str], None] = 'bdf902864461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ran_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pulsar_count', sa.Integer(), nullable=False),
    sa.Column('anomaly_count', sa.Integer(), nullable=False),
    sa.Column('insufficient_data_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pulsar_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('PSRJ', sa.String(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('TYPE', sa.String(), nullable=True),
    sa.Column('P0', sa.Float(), nullable=False),
    sa.Column('P0_ERR', sa.Float(), nullable=True),
    sa.Column('P1', sa.Float(), nullable=True),
    sa.Column('P1_ERR', sa.Float(), nullable=True),
    sa.Column('DIST', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pulsar_snapshots')
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
