"""create pulsars table

Revision ID: bdf902864461
Revises: 
Create Date: 2026-08-27 22:12:44.257392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdf902864461'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pulsars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PSRJ', sa.String(), nullable=False),
    sa.Column('classification', sa.Enum('Magnetars', 'Ordinary Pulsars', 'Millisecond Pulsars', name='classification_enum'), nullable=False),
    sa.Column('TYPE', sa.String(), nullable=True),
    sa.Column('P0', sa.Float(), nullable=False),
    sa.Column('P0_ERR', sa.Float(), nullable=True),
    sa.Column('P1', sa.Float(), nullable=True),
    sa.Column('P1_ERR', sa.Float(), nullable=True),
    sa.Column('DIST', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('PSRJ')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pulsars')
    # ### end Alembic commands ###
